### ISSUE TITLE
Provide a flatpak for Linux

### ISSUE THREAD

**Issue by dylanmccall** [space-wizards/SS14.Launcher#66]
Hi! I think it would be really fun if SS14 on Linux was available as a flatpak (and hosted on [Flathub](https://www.flathub.org/)). The existing self-contained tarball is really useful, but the advantage to publishing an app this way is it gets full desktop integration (the launcher goes in the right place), it is easy to install in many Linux distributions, and it runs in a lightweight container so we are pretty much guaranteed - if it works on one system - all of the necessary dependencies are there.

In general, especially for a project like this, it makes sense that the flatpak metadata is in another repository, but it is always better when this kind of thing has upstream's blessing :) So I started working on it over here: https://github.com/dylanmccall/com.spacestation14.Launcher. I'm happy with it at the moment. It builds and runs without too much weird stuff. Needs a desktop icon.

I'm happy to maintain this packaging metadata going forward, and if we submit it to Flathub I can grant access to the resulting repository for anyone who has commit access here. For the moment, I'm opening this issue here in order to sanity check, and to make sure I'm not stepping on anyone's toes.

**Comment by PJB3005** [comment]
This is very nice to see! While I did consider making a Flatpak, I never considered it worth the time investment since most players will use Steam anyways. I'm fine with trying to maintain it further once put into Flathub though. 

Some things I can immediately see about it (I haven't tested it, and I've never made a Flatpak package): 
* You can make it `com.spacestation14`. We have the domain, we're just barely using it because I'm slacking on moving stuff over.
* For Wayland support: you noticed the launcher doesn't support Wayland, but the game engine doesn't either. See https://github.com/space-wizards/RobustToolbox/issues/2468. TL;DR either we move to SDL2 or we fix GLFW, neither is likely to happen any time soon.
* For the desktop icon, is the problem that the desktop icon needs to match a certain styling? Otherwise you can find the images you need [here](https://github.com/space-wizards/space-station-14/tree/master/Resources/Textures/Logo) and [here](https://github.com/space-wizards/asset-dump).

**Comment by dylanmccall** [comment]
Thanks @PJB3005, that helped a bunch! Indeed, Steam is generally good enough here, so it isn't worth fussing over too much, but it is nice for certain categories of weirdos to have the option of something with less overhead :)

I renamed the repo to start with `com.spacestation14`, and grabbed icon assets from those two places. I'll play around with this for a while, make sure it's straightforward to keep up to date, and send a PR to the Flathub folks if all's well.

**Comment by dylanmccall** [comment]
Thanks for your help here @PJB3005! My next step here will be adding some bits and pieces over on that flathub repo to make updates a little more hands-off than they are, but this all appears to be in a good shape now :)
