### ISSUE TITLE
Allow servers to have their own "descriptions" defined by a cvar or whatever

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/SS14.Launcher#71]
![image](https://user-images.githubusercontent.com/67359748/178084942-83909696-8911-4ae2-ad27-84d9092c3e87.png)

See that empty space? Put some text into it and you should get something like this

![image](https://user-images.githubusercontent.com/67359748/178084975-6af3af81-6bbc-4fb4-9f65-c7c5f7964a84.png)

Of course with the correct font and actually programmed in instead of using GIMP

**Comment by ElectroJr** [comment]
IIRC adding a discord button was also discussed in the maintainer meeting, though I can't find it in the notes.
The basic gist was that as many servers currently have a discord link in the name, so just adding support for a discord button would already make the names significantly shorter.

**Comment by Just-a-Unity-Dev** [comment]
> IIRC adding a discord button was also discussed in the maintainer meeting, though I can't find it in the notes. The basic gist was that as many servers currently have a discord link in the name, so just adding support for a discord button would already make the names significantly shorter.

would also stop cramming everything into the title, like so:

[LRP][US-WEST][16+] LongAssServerNameThatICantBeBotheredToTypeOutCompletely (discord.gg/AnotherLongAssServerNameBecauseNoVanityLink)

**Comment by Just-a-Unity-Dev** [comment]
Willing to code this when I got the time

**Comment by PJB3005** [comment]
The way I was thinking of doing this is as such:

* Have the `/info` endpoint be fetched to show server description, since it's large data and we don't want to send it with status.
* Include a `desc` field in the JSON for just a regular plain-text description.
* I just merged https://github.com/space-wizards/RobustToolbox/pull/2769 which had been sitting for far too long, it can be used to do stuff like `[LRP]` and such. 
  * I figure the best way to do this would be to have standardized tags like `rp:low`, `age:18`, `region:usw`, etc... Show some nice icons for it.
* Add some sort of generic list field to store links to the `/info` JSON.
  * I'm thinking you want to have an icon identifier, link text, and link url. So like `{"icon": "discord", "text": "Discord", "url": "https://discord.gg"}`. I don't know how we would put this in the config on the game server side though. One option is to have content expose a bunch of standard CVars like `hub.url_discord` and then filling them up with an engine API on info request.

**Comment by Just-a-Unity-Dev** [comment]
I was originally gonna do this but life got in the way. Couldn't even start programming it. If someone wants to pick this up feel free to do so

**Comment by Just-a-Unity-Dev** [comment]
@PJB3005 wooooooooo!!!
